<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DB manager' => 'Manager Bazy danych',
    'Database' => 'Baza danych',
    'Dump only schema' => 'Zrzuć tylko schemat',
    'Custom dump preset' => 'Niestandardowe ustawienie zrzutu',
    'Run in background' => 'Uruchom w tle',
    'Create dump' => 'Utwórz zrzut',
    'Delete all' => 'Usuń wszystko',
    'Are you sure?' => 'Jesteś pewny?',
    'Type' => 'Typ',
    'Name' => 'Nazwa',
    'Size' => 'Rozmiar',
    'Create time' => 'Utworzony',
    'Active processes:' => 'Aktywne procesy:',
    'All dumps successfully removed.' => 'Wszystkie zrzuty zostały pomyślnie usunięte.',
    'Custom restore preset' => 'Niestandardowe ustawienie przywracania',
    'Delete' => 'Usuń',
    'Delete from storage' => 'Usuń',
    'Download' => 'Pobierz',
    'Dump deleted from storage.' => 'Zrzut usunięty.',
    'Dump deleted successfully.' => 'Zrzut usunięty pomyślnie.',
    'Dump failed.' => 'Zrzut nie powiódł się.',
    'Dump request invalid.' => 'Niepoprawne żądanie zrzutu.',
    'Dump successfully created.' => 'Zrzut został pomyślnie utworzony.',
    'Dump successfully restored.' => 'Zrzut został pomyślnie przywrócony.',
    'Dump uploaded to storage.' => 'Zrzut przesłany.',
    'Error deleting dump.' => 'Błąd podczas usuwania zrzutu.',
    'Error deleting dumps.' => 'Błąd podczas usuwania zrzutów.',
    'Process complete!' => 'Proces zakończony!',
    'Process running with pid={pid}' => 'Proces działa z pid={pid}',
    'Restore' => 'Przywróć',
    'Restore failed.' => 'Restore failed.',
    'Upload to storage' => 'Prześlij',
    'gzip' => 'gzip',
];
